name: Custom Workflow Integration

on:
  push:
    branches:
      - main # Trigger on changes to the main branch

jobs:
  custom_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Generate release notes
        run: ../scripts/generatingreleasenotes.sh
