name: Dependency Updates

on:
  #schedule:
  #  - cron: '0 0 * * *' # Run daily
  push:
    branches:
      - main

jobs:
  dependency_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check for dependency updates
        #uses: dependabot/dependabot-core@v0.163.x
        run: echo "checking for updates using dependabot"
        #with:
        #  github-token: ${{ secrets.GITHUB_TOKEN }}
        #  directory: '.' # Specify the directory containing package files
