name: Documentation Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Build documentation
        run: #npm run build-docs
            echo "building docs"

      - name: Deploy documentation
        run:  ../scripts/deployingdocs.sh
        #uses: peaceiris/actions-gh-pages@v3
        #with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
        #  publish_dir: ./docs
