name: Documentation Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build documentation
        run: #npm run build-docs
            echo "building docs"

      - name: Deploy documentation
        run: "deploying documentation"
        #uses: peaceiris/actions-gh-pages@v3
        #with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
        #  publish_dir: ./docs
