name: Scheduled Tasks

on:
  #schedule:
  #  - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main

jobs:
  run_tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run maintenance script
        run: ../scripts/run_maintenance.sh

      - name: Backup data
        run: ../scripts/backup_data.sh
        
      - name: Send notification
        run: echo "Scheduled tasks completed successfully"
